### ISSUE TITLE
MEMF_FAST

### ISSUE THREAD

**Issue by leifo** [virgill1974/Alcatraz-Soil#1]
The use of MEMF_FAST, as in main.c and data.h, will make the code fail to load on chip-only machines, which could have enough memory. 

Better use MEMF_ANY (or MEMF_PUBLIC on Kick2.0+), c.f. [Memory Attributes](http://amigadev.elowar.com/read/ADCD_2.1/Libraries_Manual_guide/node02A8.html)

**Comment by virgill1974** [comment]
Thank you Leif. 
Fixed and tested in WinUAE on unexpanded A600 and A1200.  Runs, but makes some weird glitches on those systems ;)

**Comment by virgill1974** [comment]
Thank you Leif.
Fixed and tested in WinUAE on unexpanded A600 and A1200. Runs, but makes some weird glitches on those systems ;)
